[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
vault = "CR7XqeU2TqY4p8Px9jgM3QkgE254i7Prd6x4HWT4gTR7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
